### PR TITLE
Sort GUI items alphabetically

### PR DESCRIPTION
**Pull request by Mitality**
Jsinco pls verify, I'm not that familiar with this addon

### CODE REVIEW

**Comment by Jsinco** [comment]
This sorting method will work but it’ll sort the item names after being colored, maybe strip the color or sort before they’re turned into item stacks?

**Comment by Mitality** [comment]
In my GUI they all have the same color, they can be set independently..?

**Comment by Jsinco** [comment]
Yeah, they'll take the on the color in the name of the recipe I'm pretty sure

**Comment by Mitality** [comment]
Alright, didn't know that, I'll take that into account then

**Comment by Mitality** [comment]
Now it should work even with colored names

**Comment by Mitality** [comment]
Have successfully tested it, so it can be merged imo

**Pull request merged**
